Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Layout/MultilineBlockLayout:
  Exclude:
    - spec/**/*
